name: Push
on:
  push:
    paths:
      - buildSrc/**/*
      - src/**/*
      - build.gradle.kts
      - settings.gradke.kts

jobs:
  ktlint:
    name: 💅 Kotlin code lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('build.gradle.kts', 'buildSrc/**/*', 'gradle/**/*') }}
          path: |
            gradle/
            .gradle/
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - run: gradle ktlintFormat
      - name: Commit formatting code
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          branch: main
          add: '.'
          message: 'style: linting code [skip ci]'
          push: true
  detekt:
    name: 🔍 Kotlin static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('build.gradle.kts', 'gradle/**/*', 'buildSrc/**/*') }}
          path: |
            gradle/
            .gradle/
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - run: gradle detekt
